sudo: required

language: python

services:
  - docker

python: 3.6

before_install:
  - docker --version
  - docker-compose --version

script:
    - pytest

install:
    - pip install -r requirements.txt

notifications:
  email:
    on_success: change
    on_failure: always