swagger: '2.0'

basePath: /api/1

info:
  title: {{ cookiecutter.project_name.upper() }} API
  version: '1.0'
  description: API 1.0

securityDefinitions:
  UserSecurity:
    type: apiKey
    name: API-KEY
    in: header