app:
  name: &appname {{cookiecutter.project_slug}}
  env: dev
  debug: true
  cors: true

applications:
  - common
{% if cookiecutter.users_app == 'y' %}  - users{% endif %}

databases:
  default:
    database: *appname

redis:
  default:
    host: 127.0.0.1
    port: 6379
    db: 0
    prefix: *appname
    minsize: 5
    maxsize: 10
  sessions:
    host: 127.0.0.1
    port: 6379
    db: 1
    prefix: *appname
    minsize: 5
    maxsize: 10

path:
  templates:
  - templates
  static: ../static
  media: ../media

fixtures:
{% if cookiecutter.users_app == 'y' %}- users{% endif %}