app:
  name: &appname {{cookiecutter.project_slug}}
  debug: true
  router:
    search_in_modules:
      - {{cookiecutter.project_slug}}
    cors:
      domains: '*'
  resources:
    api_1:
      prefix: /api/1
      /:
        include: api.yaml
  cleanup_ctx:
    pg: dvhb_hybrid.config.cleanup_ctx_databases
    redis: dvhb_hybrid.config.cleanup_ctx_redis
    redis-sessions: dvhb_hybrid.config.cleanup_ctx_redis_sessions

applications:
  - common

databases:
  default:
    database: *appname

redis:
  default:
    prefix: *appname
    connection:
      host: 127.0.0.1
      port: 6379
      db: 0
      minsize: 5
      maxsize: 10
  sessions:
    prefix: *appname
    connection:
      host: 127.0.0.1
      port: 6379
      db: 1
      minsize: 5
      maxsize: 10

path:
  templates:
  - templates
  static: ../static
  media: ../media
